---
build_from:
  aarch64: bbernhard/signal-cli-rest-api:latest
  amd64: bbernhard/signal-cli-rest-api:latest
  armv7: bbernhard/signal-cli-rest-api:latest
labels:
  org.opencontainers.image.title: "Signalbot"
  org.opencontainers.image.source: "https://github.com/sahelea1/ha-hacs-integration-signalbot"
